pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo("Hello")
            }
        }
        stage('Test') {
            steps {
                echo("Hello")
            }
        }
        stage('Deploy') {
            steps {
                echo("Hello")
            }
        }
    }
}